services:
  develop:
    container_name: scraper_dev
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - .:/workspaces
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true

  selenium:
    container_name: scraper_selenium
    image: selenium/standalone-chrome:4.27.0
    ports:
      - 4444:4444
      - 7900:7900
    volumes:
      - /dev/shm:/dev/shm

  app:
    container_name: scraper_app
    build: .
    ports:
      - 8888:8888
    volumes:
      - .:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
